version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:975050225555:task-definition/ecs-cicd-family:9"
        LoadBalancerInfo:
          ContainerName: "web"
          ContainerPort: 80
